export const WHITELIST_ADDRESS = process.env.NEXT_PUBLIC_WHITELIST_ADDRESS!;
export const NFT_ADDRESS = process.env.NEXT_PUBLIC_NFT_ADDRESS!;
export const TOKEN_ADDRESS = process.env.NEXT_PUBLIC_TOKEN_ADDRESS!;
