export const WHITELIST_ADDRESS = process.env.NEXT_PUBLIC_WHITELIST_ADDRESS!;
export const NFT_ADDRESS = process.env.NEXT_PUBLIC_NFT_ADDRESS!;
export const SEPOLIA_ADDRESS = process.env.NEXT_PUBLIC_SEPOLIA_ADDRESS!;
export const NFT_CONTRACT_OWNER_ADDRESS =
  process.env.NEXT_NFT_CONTRACT_OWNER_ADDRESS!;
